version: '3'
services:
  doc-loader:
    build: .
    image: quivr-doc-loader
    volumes:
      - .:/app
    ports:
      - 8022:22
    restart: always
    networks:
      - quivr_quivr_common

networks:
  quivr_quivr_common:
    external: true